# Generated by Django 2.2.24 on 2023-08-01 06:01
import phonenumbers
from django.db import migrations


def get_owners_pure_phones(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    
    for flat in Flat.objects.all():
        try:
            owner_pure_phone = phonenumbers.parse(flat.owners_phonenumber, 'RU')
        except phonenumbers.NumberParseException:
            flat.owner_pure_phone = 'Parsing owners_phonenumber error'
        else:
            if phonenumbers.is_possible_number(owner_pure_phone) and phonenumbers.is_valid_number(owner_pure_phone):
                flat.owner_pure_phone = phonenumbers.format_number(owner_pure_phone,
                                                                   phonenumbers.PhoneNumberFormat.E164)
            else:
                flat.owner_pure_phone = 'Impossible or invalid number'
        finally:
            flat.save()


class Migration(migrations.Migration):
    
    dependencies = [
        ('property', '0008_flat_owner_pure_phone'),
    ]
    
    operations = [
        migrations.RunPython(get_owners_pure_phones)
    ]
