# Generated by Django 2.2.24 on 2023-08-02 08:51

from django.db import migrations


def copy_owner_data(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')
    
    for flat in Flat.objects.all():
        Owner.objects.get_or_create(name=flat.owner,
                                    phonenumber=flat.owners_phonenumber,
                                    pure_phone=flat.owner_pure_phone)
    

class Migration(migrations.Migration):

    dependencies = [
        ('property', '0010_owner'),
    ]

    operations = [
        migrations.RunPython(copy_owner_data)
    ]
