# Generated by Django 2.2.24 on 2023-08-03 05:06

from django.db import migrations


def add_relation_flat_to_owner(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')
    
    for owner in Owner.objects.all():
        flats_owned_by_this_owner = Flat.objects.filter(owner=owner.name)
        owner.flats.add(*flats_owned_by_this_owner)
        
        
class Migration(migrations.Migration):

    dependencies = [
        ('property', '0012_auto_20230803_0805'),
    ]

    operations = [
        migrations.RunPython(add_relation_flat_to_owner)
    ]
